services:
  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: unless-stopped

  gateway-service:
    image: gateway-service
    build: ./service-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GATEWAY_USERNAME: ${GATEWAY_USERNAME}
      GATEWAY_PASSWORD: ${GATEWAY_PASSWORD}

  patient-service:
    image: patient-service
    build: ./service-patient
    restart: unless-stopped
    depends_on:
      - eureka-server
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: ${MYSQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilabo

  note-service:
    image: note-service
    build: ./service-note
    restart: unless-stopped
    depends_on:
      - eureka-server
      - mongo-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/medilabo
      GATEWAY_USERNAME: ${GATEWAY_USERNAME}
      GATEWAY_PASSWORD: ${GATEWAY_PASSWORD}
  
  diabetes-risk-service:
    image: diabetes-risk-service
    build: ./service-diabetesrisk
    restart: unless-stopped
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GATEWAY_USERNAME: ${GATEWAY_USERNAME}
      GATEWAY_PASSWORD: ${GATEWAY_PASSWORD}
  
  front-service:
    image: front-service
    build: ./service-front
    restart: unless-stopped
    depends_on:
      - eureka-server
      - gateway-service
      - patient-service
      - note-service
      - diabetes-risk-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: ${MYSQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilabo_administration
      GATEWAY_USERNAME: ${GATEWAY_USERNAME}
      GATEWAY_PASSWORD: ${GATEWAY_PASSWORD}
      APP_URL: ${APP_URL}
  
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: medilabo
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql/docker-init.sql:/docker-entrypoint-initdb.d/init.sql

  
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: medilabo
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./database/mongodb/fixtures.js:/docker-entrypoint-initdb.d/init.js:ro


volumes:
  mysql_data:
  mongo_data: